//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROACTIS.ExampleApplication.CreateInternalInvoice.p2p {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.proactis.com/proactis/webservice", ConfigurationName="p2p.XMLGatewaySoap")]
    public interface XMLGatewaySoap {
        
        // CODEGEN: Generating message contract since element name XML from namespace http://www.proactis.com/proactis/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/GetSecurityConfig", ReplyAction="*")]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetSecurityConfigResponse GetSecurityConfig(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetSecurityConfigRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/GetSecurityConfig", ReplyAction="*")]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetSecurityConfigResponse> GetSecurityConfigAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetSecurityConfigRequest request);
        
        // CODEGEN: Generating message contract since element name XML from namespace http://www.proactis.com/proactis/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/GetOffLineExpenseConfig", ReplyAction="*")]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetOffLineExpenseConfigResponse GetOffLineExpenseConfig(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetOffLineExpenseConfigRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/GetOffLineExpenseConfig", ReplyAction="*")]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetOffLineExpenseConfigResponse> GetOffLineExpenseConfigAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetOffLineExpenseConfigRequest request);
        
        // CODEGEN: Generating message contract since element name DocumentXML from namespace http://www.proactis.com/proactis/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/ImportDocument", ReplyAction="*")]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ImportDocumentResponse ImportDocument(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ImportDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/ImportDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ImportDocumentResponse> ImportDocumentAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ImportDocumentRequest request);
        
        // CODEGEN: Generating message contract since element name DocumentXML from namespace http://www.proactis.com/proactis/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/ExportDocument", ReplyAction="*")]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ExportDocumentResponse ExportDocument(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ExportDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/ExportDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ExportDocumentResponse> ExportDocumentAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ExportDocumentRequest request);
        
        // CODEGEN: Generating message contract since element name ListDatabasesResult from namespace http://www.proactis.com/proactis/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/ListDatabases", ReplyAction="*")]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ListDatabasesResponse ListDatabases(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ListDatabasesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/ListDatabases", ReplyAction="*")]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ListDatabasesResponse> ListDatabasesAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ListDatabasesRequest request);
        
        // CODEGEN: Generating message contract since element name UserXML from namespace http://www.proactis.com/proactis/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/AuthenticateUser", ReplyAction="*")]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthenticateUserResponse AuthenticateUser(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/AuthenticateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthenticateUserResponse> AuthenticateUserAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthenticateUserRequest request);
        
        // CODEGEN: Generating message contract since element name AcknowledgmentXML from namespace http://www.proactis.com/proactis/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/OrderAcknowledgment", ReplyAction="*")]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrderAcknowledgmentResponse OrderAcknowledgment(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrderAcknowledgmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/OrderAcknowledgment", ReplyAction="*")]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrderAcknowledgmentResponse> OrderAcknowledgmentAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrderAcknowledgmentRequest request);
        
        // CODEGEN: Generating message contract since element name UserXML from namespace http://www.proactis.com/proactis/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/GetExportDefinition", ReplyAction="*")]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetExportDefinitionResponse GetExportDefinition(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetExportDefinitionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/GetExportDefinition", ReplyAction="*")]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetExportDefinitionResponse> GetExportDefinitionAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetExportDefinitionRequest request);
        
        // CODEGEN: Generating message contract since element name DocumentXML from namespace http://www.proactis.com/proactis/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/RunExport", ReplyAction="*")]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.RunExportResponse RunExport(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.RunExportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/RunExport", ReplyAction="*")]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.RunExportResponse> RunExportAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.RunExportRequest request);
        
        // CODEGEN: Generating message contract since element name ControlXML from namespace http://www.proactis.com/proactis/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/CancelOrder", ReplyAction="*")]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderResponse CancelOrder(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/CancelOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderResponse> CancelOrderAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderRequest request);
        
        // CODEGEN: Generating message contract since element name ControlXML from namespace http://www.proactis.com/proactis/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/CancelOrderByGUID", ReplyAction="*")]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderByGUIDResponse CancelOrderByGUID(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderByGUIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/CancelOrderByGUID", ReplyAction="*")]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderByGUIDResponse> CancelOrderByGUIDAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderByGUIDRequest request);
        
        // CODEGEN: Generating message contract since element name ControlXML from namespace http://www.proactis.com/proactis/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/CloseOrderForInvoicing", ReplyAction="*")]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CloseOrderForInvoicingResponse CloseOrderForInvoicing(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CloseOrderForInvoicingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/CloseOrderForInvoicing", ReplyAction="*")]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CloseOrderForInvoicingResponse> CloseOrderForInvoicingAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CloseOrderForInvoicingRequest request);
        
        // CODEGEN: Generating message contract since element name ControlXML from namespace http://www.proactis.com/proactis/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/AuthoriseOrder", ReplyAction="*")]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthoriseOrderResponse AuthoriseOrder(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthoriseOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/AuthoriseOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthoriseOrderResponse> AuthoriseOrderAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthoriseOrderRequest request);
        
        // CODEGEN: Generating message contract since element name ControlXML from namespace http://www.proactis.com/proactis/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/OrdersForAuthorisation", ReplyAction="*")]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrdersForAuthorisationResponse OrdersForAuthorisation(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrdersForAuthorisationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.proactis.com/proactis/webservice/OrdersForAuthorisation", ReplyAction="*")]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrdersForAuthorisationResponse> OrdersForAuthorisationAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrdersForAuthorisationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSecurityConfigRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSecurityConfig", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetSecurityConfigRequestBody Body;
        
        public GetSecurityConfigRequest() {
        }
        
        public GetSecurityConfigRequest(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetSecurityConfigRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class GetSecurityConfigRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XML;
        
        public GetSecurityConfigRequestBody() {
        }
        
        public GetSecurityConfigRequestBody(string XML) {
            this.XML = XML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSecurityConfigResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSecurityConfigResponse", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetSecurityConfigResponseBody Body;
        
        public GetSecurityConfigResponse() {
        }
        
        public GetSecurityConfigResponse(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetSecurityConfigResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class GetSecurityConfigResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSecurityConfigResult;
        
        public GetSecurityConfigResponseBody() {
        }
        
        public GetSecurityConfigResponseBody(string GetSecurityConfigResult) {
            this.GetSecurityConfigResult = GetSecurityConfigResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOffLineExpenseConfigRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOffLineExpenseConfig", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetOffLineExpenseConfigRequestBody Body;
        
        public GetOffLineExpenseConfigRequest() {
        }
        
        public GetOffLineExpenseConfigRequest(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetOffLineExpenseConfigRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class GetOffLineExpenseConfigRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XML;
        
        public GetOffLineExpenseConfigRequestBody() {
        }
        
        public GetOffLineExpenseConfigRequestBody(string XML) {
            this.XML = XML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOffLineExpenseConfigResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOffLineExpenseConfigResponse", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetOffLineExpenseConfigResponseBody Body;
        
        public GetOffLineExpenseConfigResponse() {
        }
        
        public GetOffLineExpenseConfigResponse(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetOffLineExpenseConfigResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class GetOffLineExpenseConfigResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetOffLineExpenseConfigResult;
        
        public GetOffLineExpenseConfigResponseBody() {
        }
        
        public GetOffLineExpenseConfigResponseBody(string GetOffLineExpenseConfigResult) {
            this.GetOffLineExpenseConfigResult = GetOffLineExpenseConfigResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportDocument", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ImportDocumentRequestBody Body;
        
        public ImportDocumentRequest() {
        }
        
        public ImportDocumentRequest(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ImportDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class ImportDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DocumentXML;
        
        public ImportDocumentRequestBody() {
        }
        
        public ImportDocumentRequestBody(string DocumentXML) {
            this.DocumentXML = DocumentXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportDocumentResponse", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ImportDocumentResponseBody Body;
        
        public ImportDocumentResponse() {
        }
        
        public ImportDocumentResponse(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ImportDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class ImportDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ImportDocumentResult;
        
        public ImportDocumentResponseBody() {
        }
        
        public ImportDocumentResponseBody(string ImportDocumentResult) {
            this.ImportDocumentResult = ImportDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExportDocument", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ExportDocumentRequestBody Body;
        
        public ExportDocumentRequest() {
        }
        
        public ExportDocumentRequest(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ExportDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class ExportDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DocumentXML;
        
        public ExportDocumentRequestBody() {
        }
        
        public ExportDocumentRequestBody(string DocumentXML) {
            this.DocumentXML = DocumentXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExportDocumentResponse", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ExportDocumentResponseBody Body;
        
        public ExportDocumentResponse() {
        }
        
        public ExportDocumentResponse(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ExportDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class ExportDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExportDocumentResult;
        
        public ExportDocumentResponseBody() {
        }
        
        public ExportDocumentResponseBody(string ExportDocumentResult) {
            this.ExportDocumentResult = ExportDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListDatabasesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListDatabases", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ListDatabasesRequestBody Body;
        
        public ListDatabasesRequest() {
        }
        
        public ListDatabasesRequest(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ListDatabasesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListDatabasesRequestBody {
        
        public ListDatabasesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListDatabasesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListDatabasesResponse", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ListDatabasesResponseBody Body;
        
        public ListDatabasesResponse() {
        }
        
        public ListDatabasesResponse(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ListDatabasesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class ListDatabasesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ListDatabasesResult;
        
        public ListDatabasesResponseBody() {
        }
        
        public ListDatabasesResponseBody(string ListDatabasesResult) {
            this.ListDatabasesResult = ListDatabasesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUser", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthenticateUserRequestBody Body;
        
        public AuthenticateUserRequest() {
        }
        
        public AuthenticateUserRequest(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthenticateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class AuthenticateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserXML;
        
        public AuthenticateUserRequestBody() {
        }
        
        public AuthenticateUserRequestBody(string UserXML) {
            this.UserXML = UserXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserResponse", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthenticateUserResponseBody Body;
        
        public AuthenticateUserResponse() {
        }
        
        public AuthenticateUserResponse(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthenticateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class AuthenticateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AuthenticateUserResult;
        
        public AuthenticateUserResponseBody() {
        }
        
        public AuthenticateUserResponseBody(bool AuthenticateUserResult) {
            this.AuthenticateUserResult = AuthenticateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrderAcknowledgmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrderAcknowledgment", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrderAcknowledgmentRequestBody Body;
        
        public OrderAcknowledgmentRequest() {
        }
        
        public OrderAcknowledgmentRequest(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrderAcknowledgmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class OrderAcknowledgmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AcknowledgmentXML;
        
        public OrderAcknowledgmentRequestBody() {
        }
        
        public OrderAcknowledgmentRequestBody(string AcknowledgmentXML) {
            this.AcknowledgmentXML = AcknowledgmentXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrderAcknowledgmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrderAcknowledgmentResponse", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrderAcknowledgmentResponseBody Body;
        
        public OrderAcknowledgmentResponse() {
        }
        
        public OrderAcknowledgmentResponse(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrderAcknowledgmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class OrderAcknowledgmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OrderAcknowledgmentResult;
        
        public OrderAcknowledgmentResponseBody() {
        }
        
        public OrderAcknowledgmentResponseBody(string OrderAcknowledgmentResult) {
            this.OrderAcknowledgmentResult = OrderAcknowledgmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExportDefinitionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExportDefinition", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetExportDefinitionRequestBody Body;
        
        public GetExportDefinitionRequest() {
        }
        
        public GetExportDefinitionRequest(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetExportDefinitionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class GetExportDefinitionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserXML;
        
        public GetExportDefinitionRequestBody() {
        }
        
        public GetExportDefinitionRequestBody(string UserXML) {
            this.UserXML = UserXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExportDefinitionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExportDefinitionResponse", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetExportDefinitionResponseBody Body;
        
        public GetExportDefinitionResponse() {
        }
        
        public GetExportDefinitionResponse(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetExportDefinitionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class GetExportDefinitionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExportDefinitionResult;
        
        public GetExportDefinitionResponseBody() {
        }
        
        public GetExportDefinitionResponseBody(string GetExportDefinitionResult) {
            this.GetExportDefinitionResult = GetExportDefinitionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunExportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunExport", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.RunExportRequestBody Body;
        
        public RunExportRequest() {
        }
        
        public RunExportRequest(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.RunExportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class RunExportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DocumentXML;
        
        public RunExportRequestBody() {
        }
        
        public RunExportRequestBody(string DocumentXML) {
            this.DocumentXML = DocumentXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunExportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunExportResponse", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.RunExportResponseBody Body;
        
        public RunExportResponse() {
        }
        
        public RunExportResponse(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.RunExportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class RunExportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RunExportResult;
        
        public RunExportResponseBody() {
        }
        
        public RunExportResponseBody(string RunExportResult) {
            this.RunExportResult = RunExportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelOrder", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderRequestBody Body;
        
        public CancelOrderRequest() {
        }
        
        public CancelOrderRequest(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class CancelOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ControlXML;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TemplateLabel;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int OrderNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DisplayNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CancellationReason;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Comments;
        
        public CancelOrderRequestBody() {
        }
        
        public CancelOrderRequestBody(string ControlXML, string TemplateLabel, int OrderNumber, string DisplayNumber, string CancellationReason, string Comments) {
            this.ControlXML = ControlXML;
            this.TemplateLabel = TemplateLabel;
            this.OrderNumber = OrderNumber;
            this.DisplayNumber = DisplayNumber;
            this.CancellationReason = CancellationReason;
            this.Comments = Comments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelOrderResponse", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderResponseBody Body;
        
        public CancelOrderResponse() {
        }
        
        public CancelOrderResponse(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CancelOrderResponseBody {
        
        public CancelOrderResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelOrderByGUIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelOrderByGUID", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderByGUIDRequestBody Body;
        
        public CancelOrderByGUIDRequest() {
        }
        
        public CancelOrderByGUIDRequest(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderByGUIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class CancelOrderByGUIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ControlXML;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OrderGUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CancellationReason;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Comments;
        
        public CancelOrderByGUIDRequestBody() {
        }
        
        public CancelOrderByGUIDRequestBody(string ControlXML, string OrderGUID, string CancellationReason, string Comments) {
            this.ControlXML = ControlXML;
            this.OrderGUID = OrderGUID;
            this.CancellationReason = CancellationReason;
            this.Comments = Comments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelOrderByGUIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelOrderByGUIDResponse", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderByGUIDResponseBody Body;
        
        public CancelOrderByGUIDResponse() {
        }
        
        public CancelOrderByGUIDResponse(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderByGUIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CancelOrderByGUIDResponseBody {
        
        public CancelOrderByGUIDResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CloseOrderForInvoicingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CloseOrderForInvoicing", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CloseOrderForInvoicingRequestBody Body;
        
        public CloseOrderForInvoicingRequest() {
        }
        
        public CloseOrderForInvoicingRequest(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CloseOrderForInvoicingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class CloseOrderForInvoicingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ControlXML;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OrderGUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Comments;
        
        public CloseOrderForInvoicingRequestBody() {
        }
        
        public CloseOrderForInvoicingRequestBody(string ControlXML, string OrderGUID, string Comments) {
            this.ControlXML = ControlXML;
            this.OrderGUID = OrderGUID;
            this.Comments = Comments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CloseOrderForInvoicingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CloseOrderForInvoicingResponse", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CloseOrderForInvoicingResponseBody Body;
        
        public CloseOrderForInvoicingResponse() {
        }
        
        public CloseOrderForInvoicingResponse(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CloseOrderForInvoicingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CloseOrderForInvoicingResponseBody {
        
        public CloseOrderForInvoicingResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthoriseOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthoriseOrder", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthoriseOrderRequestBody Body;
        
        public AuthoriseOrderRequest() {
        }
        
        public AuthoriseOrderRequest(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthoriseOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class AuthoriseOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ControlXML;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OrderGUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Comments;
        
        public AuthoriseOrderRequestBody() {
        }
        
        public AuthoriseOrderRequestBody(string ControlXML, string OrderGUID, string Comments) {
            this.ControlXML = ControlXML;
            this.OrderGUID = OrderGUID;
            this.Comments = Comments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthoriseOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthoriseOrderResponse", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthoriseOrderResponseBody Body;
        
        public AuthoriseOrderResponse() {
        }
        
        public AuthoriseOrderResponse(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthoriseOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AuthoriseOrderResponseBody {
        
        public AuthoriseOrderResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrdersForAuthorisationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrdersForAuthorisation", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrdersForAuthorisationRequestBody Body;
        
        public OrdersForAuthorisationRequest() {
        }
        
        public OrdersForAuthorisationRequest(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrdersForAuthorisationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class OrdersForAuthorisationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ControlXML;
        
        public OrdersForAuthorisationRequestBody() {
        }
        
        public OrdersForAuthorisationRequestBody(string ControlXML) {
            this.ControlXML = ControlXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrdersForAuthorisationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrdersForAuthorisationResponse", Namespace="http://www.proactis.com/proactis/webservice", Order=0)]
        public PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrdersForAuthorisationResponseBody Body;
        
        public OrdersForAuthorisationResponse() {
        }
        
        public OrdersForAuthorisationResponse(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrdersForAuthorisationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.proactis.com/proactis/webservice")]
    public partial class OrdersForAuthorisationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OrdersForAuthorisationResult;
        
        public OrdersForAuthorisationResponseBody() {
        }
        
        public OrdersForAuthorisationResponseBody(string OrdersForAuthorisationResult) {
            this.OrdersForAuthorisationResult = OrdersForAuthorisationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface XMLGatewaySoapChannel : PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XMLGatewaySoapClient : System.ServiceModel.ClientBase<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap>, PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap {
        
        public XMLGatewaySoapClient() {
        }
        
        public XMLGatewaySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XMLGatewaySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XMLGatewaySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XMLGatewaySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetSecurityConfigResponse PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.GetSecurityConfig(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetSecurityConfigRequest request) {
            return base.Channel.GetSecurityConfig(request);
        }
        
        public string GetSecurityConfig(string XML) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetSecurityConfigRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetSecurityConfigRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetSecurityConfigRequestBody();
            inValue.Body.XML = XML;
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetSecurityConfigResponse retVal = ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).GetSecurityConfig(inValue);
            return retVal.Body.GetSecurityConfigResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetSecurityConfigResponse> PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.GetSecurityConfigAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetSecurityConfigRequest request) {
            return base.Channel.GetSecurityConfigAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetSecurityConfigResponse> GetSecurityConfigAsync(string XML) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetSecurityConfigRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetSecurityConfigRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetSecurityConfigRequestBody();
            inValue.Body.XML = XML;
            return ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).GetSecurityConfigAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetOffLineExpenseConfigResponse PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.GetOffLineExpenseConfig(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetOffLineExpenseConfigRequest request) {
            return base.Channel.GetOffLineExpenseConfig(request);
        }
        
        public string GetOffLineExpenseConfig(string XML) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetOffLineExpenseConfigRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetOffLineExpenseConfigRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetOffLineExpenseConfigRequestBody();
            inValue.Body.XML = XML;
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetOffLineExpenseConfigResponse retVal = ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).GetOffLineExpenseConfig(inValue);
            return retVal.Body.GetOffLineExpenseConfigResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetOffLineExpenseConfigResponse> PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.GetOffLineExpenseConfigAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetOffLineExpenseConfigRequest request) {
            return base.Channel.GetOffLineExpenseConfigAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetOffLineExpenseConfigResponse> GetOffLineExpenseConfigAsync(string XML) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetOffLineExpenseConfigRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetOffLineExpenseConfigRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetOffLineExpenseConfigRequestBody();
            inValue.Body.XML = XML;
            return ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).GetOffLineExpenseConfigAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ImportDocumentResponse PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.ImportDocument(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ImportDocumentRequest request) {
            return base.Channel.ImportDocument(request);
        }
        
        public string ImportDocument(string DocumentXML) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ImportDocumentRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ImportDocumentRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ImportDocumentRequestBody();
            inValue.Body.DocumentXML = DocumentXML;
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ImportDocumentResponse retVal = ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).ImportDocument(inValue);
            return retVal.Body.ImportDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ImportDocumentResponse> PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.ImportDocumentAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ImportDocumentRequest request) {
            return base.Channel.ImportDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ImportDocumentResponse> ImportDocumentAsync(string DocumentXML) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ImportDocumentRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ImportDocumentRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ImportDocumentRequestBody();
            inValue.Body.DocumentXML = DocumentXML;
            return ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).ImportDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ExportDocumentResponse PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.ExportDocument(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ExportDocumentRequest request) {
            return base.Channel.ExportDocument(request);
        }
        
        public string ExportDocument(string DocumentXML) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ExportDocumentRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ExportDocumentRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ExportDocumentRequestBody();
            inValue.Body.DocumentXML = DocumentXML;
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ExportDocumentResponse retVal = ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).ExportDocument(inValue);
            return retVal.Body.ExportDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ExportDocumentResponse> PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.ExportDocumentAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ExportDocumentRequest request) {
            return base.Channel.ExportDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ExportDocumentResponse> ExportDocumentAsync(string DocumentXML) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ExportDocumentRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ExportDocumentRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ExportDocumentRequestBody();
            inValue.Body.DocumentXML = DocumentXML;
            return ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).ExportDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ListDatabasesResponse PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.ListDatabases(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ListDatabasesRequest request) {
            return base.Channel.ListDatabases(request);
        }
        
        public string ListDatabases() {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ListDatabasesRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ListDatabasesRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ListDatabasesRequestBody();
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ListDatabasesResponse retVal = ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).ListDatabases(inValue);
            return retVal.Body.ListDatabasesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ListDatabasesResponse> PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.ListDatabasesAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ListDatabasesRequest request) {
            return base.Channel.ListDatabasesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ListDatabasesResponse> ListDatabasesAsync() {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ListDatabasesRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ListDatabasesRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.ListDatabasesRequestBody();
            return ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).ListDatabasesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthenticateUserResponse PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.AuthenticateUser(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUser(request);
        }
        
        public bool AuthenticateUser(string UserXML) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthenticateUserRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthenticateUserRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthenticateUserRequestBody();
            inValue.Body.UserXML = UserXML;
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthenticateUserResponse retVal = ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).AuthenticateUser(inValue);
            return retVal.Body.AuthenticateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthenticateUserResponse> PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.AuthenticateUserAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthenticateUserResponse> AuthenticateUserAsync(string UserXML) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthenticateUserRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthenticateUserRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthenticateUserRequestBody();
            inValue.Body.UserXML = UserXML;
            return ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).AuthenticateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrderAcknowledgmentResponse PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.OrderAcknowledgment(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrderAcknowledgmentRequest request) {
            return base.Channel.OrderAcknowledgment(request);
        }
        
        public string OrderAcknowledgment(string AcknowledgmentXML) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrderAcknowledgmentRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrderAcknowledgmentRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrderAcknowledgmentRequestBody();
            inValue.Body.AcknowledgmentXML = AcknowledgmentXML;
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrderAcknowledgmentResponse retVal = ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).OrderAcknowledgment(inValue);
            return retVal.Body.OrderAcknowledgmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrderAcknowledgmentResponse> PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.OrderAcknowledgmentAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrderAcknowledgmentRequest request) {
            return base.Channel.OrderAcknowledgmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrderAcknowledgmentResponse> OrderAcknowledgmentAsync(string AcknowledgmentXML) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrderAcknowledgmentRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrderAcknowledgmentRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrderAcknowledgmentRequestBody();
            inValue.Body.AcknowledgmentXML = AcknowledgmentXML;
            return ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).OrderAcknowledgmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetExportDefinitionResponse PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.GetExportDefinition(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetExportDefinitionRequest request) {
            return base.Channel.GetExportDefinition(request);
        }
        
        public string GetExportDefinition(string UserXML) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetExportDefinitionRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetExportDefinitionRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetExportDefinitionRequestBody();
            inValue.Body.UserXML = UserXML;
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetExportDefinitionResponse retVal = ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).GetExportDefinition(inValue);
            return retVal.Body.GetExportDefinitionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetExportDefinitionResponse> PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.GetExportDefinitionAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetExportDefinitionRequest request) {
            return base.Channel.GetExportDefinitionAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetExportDefinitionResponse> GetExportDefinitionAsync(string UserXML) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetExportDefinitionRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetExportDefinitionRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.GetExportDefinitionRequestBody();
            inValue.Body.UserXML = UserXML;
            return ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).GetExportDefinitionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.RunExportResponse PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.RunExport(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.RunExportRequest request) {
            return base.Channel.RunExport(request);
        }
        
        public string RunExport(string DocumentXML) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.RunExportRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.RunExportRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.RunExportRequestBody();
            inValue.Body.DocumentXML = DocumentXML;
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.RunExportResponse retVal = ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).RunExport(inValue);
            return retVal.Body.RunExportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.RunExportResponse> PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.RunExportAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.RunExportRequest request) {
            return base.Channel.RunExportAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.RunExportResponse> RunExportAsync(string DocumentXML) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.RunExportRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.RunExportRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.RunExportRequestBody();
            inValue.Body.DocumentXML = DocumentXML;
            return ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).RunExportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderResponse PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.CancelOrder(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderRequest request) {
            return base.Channel.CancelOrder(request);
        }
        
        public void CancelOrder(string ControlXML, string TemplateLabel, int OrderNumber, string DisplayNumber, string CancellationReason, string Comments) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderRequestBody();
            inValue.Body.ControlXML = ControlXML;
            inValue.Body.TemplateLabel = TemplateLabel;
            inValue.Body.OrderNumber = OrderNumber;
            inValue.Body.DisplayNumber = DisplayNumber;
            inValue.Body.CancellationReason = CancellationReason;
            inValue.Body.Comments = Comments;
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderResponse retVal = ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).CancelOrder(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderResponse> PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.CancelOrderAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderRequest request) {
            return base.Channel.CancelOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderResponse> CancelOrderAsync(string ControlXML, string TemplateLabel, int OrderNumber, string DisplayNumber, string CancellationReason, string Comments) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderRequestBody();
            inValue.Body.ControlXML = ControlXML;
            inValue.Body.TemplateLabel = TemplateLabel;
            inValue.Body.OrderNumber = OrderNumber;
            inValue.Body.DisplayNumber = DisplayNumber;
            inValue.Body.CancellationReason = CancellationReason;
            inValue.Body.Comments = Comments;
            return ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).CancelOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderByGUIDResponse PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.CancelOrderByGUID(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderByGUIDRequest request) {
            return base.Channel.CancelOrderByGUID(request);
        }
        
        public void CancelOrderByGUID(string ControlXML, string OrderGUID, string CancellationReason, string Comments) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderByGUIDRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderByGUIDRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderByGUIDRequestBody();
            inValue.Body.ControlXML = ControlXML;
            inValue.Body.OrderGUID = OrderGUID;
            inValue.Body.CancellationReason = CancellationReason;
            inValue.Body.Comments = Comments;
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderByGUIDResponse retVal = ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).CancelOrderByGUID(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderByGUIDResponse> PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.CancelOrderByGUIDAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderByGUIDRequest request) {
            return base.Channel.CancelOrderByGUIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderByGUIDResponse> CancelOrderByGUIDAsync(string ControlXML, string OrderGUID, string CancellationReason, string Comments) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderByGUIDRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderByGUIDRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CancelOrderByGUIDRequestBody();
            inValue.Body.ControlXML = ControlXML;
            inValue.Body.OrderGUID = OrderGUID;
            inValue.Body.CancellationReason = CancellationReason;
            inValue.Body.Comments = Comments;
            return ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).CancelOrderByGUIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CloseOrderForInvoicingResponse PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.CloseOrderForInvoicing(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CloseOrderForInvoicingRequest request) {
            return base.Channel.CloseOrderForInvoicing(request);
        }
        
        public void CloseOrderForInvoicing(string ControlXML, string OrderGUID, string Comments) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CloseOrderForInvoicingRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CloseOrderForInvoicingRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CloseOrderForInvoicingRequestBody();
            inValue.Body.ControlXML = ControlXML;
            inValue.Body.OrderGUID = OrderGUID;
            inValue.Body.Comments = Comments;
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CloseOrderForInvoicingResponse retVal = ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).CloseOrderForInvoicing(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CloseOrderForInvoicingResponse> PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.CloseOrderForInvoicingAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CloseOrderForInvoicingRequest request) {
            return base.Channel.CloseOrderForInvoicingAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CloseOrderForInvoicingResponse> CloseOrderForInvoicingAsync(string ControlXML, string OrderGUID, string Comments) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CloseOrderForInvoicingRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CloseOrderForInvoicingRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.CloseOrderForInvoicingRequestBody();
            inValue.Body.ControlXML = ControlXML;
            inValue.Body.OrderGUID = OrderGUID;
            inValue.Body.Comments = Comments;
            return ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).CloseOrderForInvoicingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthoriseOrderResponse PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.AuthoriseOrder(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthoriseOrderRequest request) {
            return base.Channel.AuthoriseOrder(request);
        }
        
        public void AuthoriseOrder(string ControlXML, string OrderGUID, string Comments) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthoriseOrderRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthoriseOrderRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthoriseOrderRequestBody();
            inValue.Body.ControlXML = ControlXML;
            inValue.Body.OrderGUID = OrderGUID;
            inValue.Body.Comments = Comments;
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthoriseOrderResponse retVal = ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).AuthoriseOrder(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthoriseOrderResponse> PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.AuthoriseOrderAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthoriseOrderRequest request) {
            return base.Channel.AuthoriseOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthoriseOrderResponse> AuthoriseOrderAsync(string ControlXML, string OrderGUID, string Comments) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthoriseOrderRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthoriseOrderRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.AuthoriseOrderRequestBody();
            inValue.Body.ControlXML = ControlXML;
            inValue.Body.OrderGUID = OrderGUID;
            inValue.Body.Comments = Comments;
            return ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).AuthoriseOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrdersForAuthorisationResponse PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.OrdersForAuthorisation(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrdersForAuthorisationRequest request) {
            return base.Channel.OrdersForAuthorisation(request);
        }
        
        public string OrdersForAuthorisation(string ControlXML) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrdersForAuthorisationRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrdersForAuthorisationRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrdersForAuthorisationRequestBody();
            inValue.Body.ControlXML = ControlXML;
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrdersForAuthorisationResponse retVal = ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).OrdersForAuthorisation(inValue);
            return retVal.Body.OrdersForAuthorisationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrdersForAuthorisationResponse> PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap.OrdersForAuthorisationAsync(PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrdersForAuthorisationRequest request) {
            return base.Channel.OrdersForAuthorisationAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrdersForAuthorisationResponse> OrdersForAuthorisationAsync(string ControlXML) {
            PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrdersForAuthorisationRequest inValue = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrdersForAuthorisationRequest();
            inValue.Body = new PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.OrdersForAuthorisationRequestBody();
            inValue.Body.ControlXML = ControlXML;
            return ((PROACTIS.ExampleApplication.CreateInternalInvoice.p2p.XMLGatewaySoap)(this)).OrdersForAuthorisationAsync(inValue);
        }
    }
}
